steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'functions deploy slugify_util --runtime=python310 --region=us-central1 --source="./src/" --entry-point=slugify --trigger-http --allow-unauthenticated'