steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: 'bash'
    args: ['-c', 'gcloud functions deploy slugify_util --runtime=python310 --region=us-central1 --source="./src/" --entry-point=slugify --trigger-http --allow-unauthenticated']